#!/bin/sh

bat=/sys/class/power_supply/BAT1/
per="$(cat "$bat/capacity")"
status="$(cat "$bat/status")"

icon() {

[ $status = Charging ] && echo "" && exit
[ $status = Full ] && echo "" && exit
[ $status = Not charging ] && echo "" && exit

if [ "$per" -gt "90" ]; then
	icon=""
elif [ "$per" -gt "60" ]; then
	icon=""
elif [ "$per" -gt "35" ]; then
	icon=""
elif [ "$per" -gt "15" ]; then
	icon=""
elif [ "$per" -gt "10" ]; then
	icon=""
elif [ "$per" -gt "6" ]; then
	icon=""
	notify-send -u normal "Battery Low" "Battery at $per%, Connect Charger Soon"
elif [ "$per" -gt "0" ]; then
	icon=""
	notify-send -u critical "Battery Critically Low" "Battery at $per%, Connect Charger"
else
        echo  && exit
fi
echo "$icon"
}

percent() {
echo $per
}

status() {
echo $status
}

[ "$1" = "icon" ] && icon && exit
[ "$1" = "percent" ] && percent && exit
[ "$1" = "status" ] && status && exit
exit
